name: GPUMonitorIOS
options:
  bundleIdPrefix: com.gpumonitor
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true

targets:
  GPUMonitorIOS:
    type: application
    platform: iOS
    sources:
      - Sources
    resources:
      - servers.json
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.gpumonitor.ios
      PRODUCT_NAME: GPU Monitor
      INFOPLIST_FILE: Info.plist
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      SWIFT_VERSION: "5.9"
      TARGETED_DEVICE_FAMILY: "1,2"
      SUPPORTS_MACCATALYST: false
      IPHONEOS_DEPLOYMENT_TARGET: "17.0"
      CODE_SIGN_STYLE: Automatic
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
